name: Scheduled Playwright Test

on:
  schedule:
    - cron: '00 02 * * *'  # Run at 11:55 UTC every day

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.20'  # Specify Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: |
          mkdir -p reports  # Create reports directory
          npx playwright test --reporter=html --output=reports  # Specify reports directory

      - name: List files in reports directory
        run: ls -la reports/

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: reports/

      - name: Send email with Playwright report
        uses: dawidd6/action-send-mail@v3
        with:
          from: ${{ secrets.EMAIL_FROM }}  # Use secrets for sensitive information
          to: ${{ secrets.EMAIL_TO }}
          subject: Playwright Test Report
          body: Please find the attached Playwright test report.
          attachments: reports/*.html  # Attach HTML report
          smtp-server: ${{ secrets.SMTP_SERVER }}
          smtp-port: ${{ secrets.SMTP_PORT }}
          smtp-username: ${{ secrets.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}

